server:
  port: 8082

spring:
  application:
    name: cairin-javaspringboot-api
  datasource:
    url: jdbc:mysql://localhost:3306/cairin_javaspringboot_api
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimumIdle: 2
      maximumPoolSize: 5
      cachePrepStmts: true
      prepStmChaceSize: 250
      prepStmChaceSqlLimit: 2048
      useServerPrepStmts: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true